version: 2.1

jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-pkg-cache
    - run: go vet -v ./...
    - run: go test -v ./...
    - run: go install -v ./...
    - run: 
        name: "Build All"
        command: |
          cp VERSION config.sample.yml dist/
          bash build.sh $(cat VERSION)
    - save_cache:
        key: v1-pkg-cache
        paths:
        - "/go/pkg"
    - store_artifacts:
        path: config.sample.yml
        destination: config.sample.yml
    - store_artifacts:
        path: dist
        destination: ''
    - persist_to_workspace:
        root: dist
        paths:
        - '*'
  publish-github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: ./artifacts
    - run:
        name: "Publish Release on GitHub"
        command: |
          VERSION=$(cat ./artifacts/VERSION)
          rm ./artifacts/VERSION
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: /.*/
          tags:
             only: /.*/
    - publish-github-release:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v[0-9.]+$/
