version: 2.1

jobs:
  test:
    docker:
    - image: circleci/golang:1.12
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-pkg-cache
    - run: go vet -v ./...
    - run: go test -v ./...
    - save_cache:
        key: v1-pkg-cache
        paths:
        - "/go/pkg"
  build:
    docker:
    - image: circleci/golang:1.12
    steps:
    - checkout
    - run: go get -u github.com/mitchellh/gox
    - restore_cache:
        keys:
        - v1-pkg-cache
    - run: 
        name: "Build (amd64)"
        command: gox -os="linux darwin windows" -arch="amd64" -output="dist/screeps-launcher_${CIRCLE_TAG-${CIRCLE_SHA1:0:6}}_{{.OS}}_{{.Arch}}" cmd/screeps-launcher/
    - run: 
        name: "Build (arm,arm64)"
        command: gox -os="linux" -arch="arm arm64" -output="dist/screeps-launcher_${CIRCLE_TAG-${CIRCLE_SHA1:0:6}}_{{.OS}}_{{.Arch}}" cmd/screeps-launcher/
    - save_cache:
        key: v1-pkg-cache
        paths:
        - "/go/pkg"
    - store_artifacts:
        path: config.sample.yml
        destination: config.sample.yml
    - store_artifacts:
        path: dist
        destination: ''
    - persist_to_workspace:
        root: dist
        paths:
        - '*'
  publish-github-release:
    docker:
    - image: cibuilds/github:0.10
    steps:
    - attach_workspace:
        at: ./artifacts
    - run:
        name: "Publish Release on GitHub"
        command: |
          VERSION=${CIRCLE_TAG}
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  main:
    jobs:
    - test:
        filters:
          branches:
            only: /.*/
          tags:
             only: /.*/
    - build:
        requires:
        - test
        filters:
          branches:
            only: /.*/
          tags:
             only: /.*/
    - publish-github-release:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v[0-9.]+$/
